name: ExtraCI

on:
  push:

jobs:
  calc-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20.x


      - name: Install packages
        run: npm ci

      - name: Calculate coverage
        run: npx jest --coverage=true

  extra-node-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 23.x]
        os: [ubuntu-22.04, ubuntu-24.04]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.1
        with:
          node-version: ${{ matrix.node-version }}


      - name: Install packages
        run: npm ci

      - name: Run tests
        run: npx jest