name: Tests

on:
  push:

jobs:
  main-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]
        os: [ubuntu-22.04]
        shard: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm ci

      - name: Install Jest
        run: npm install --location=global jest

      - name: Run tests
        run: jest --shard=${{ matrix.shard }}/10 --runInBand

  calc-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20.x


      - name: Install packages
        run: npm ci

      - name: Install Jest
        run: npm install --location=global jest

      - name: Calculate coverage
        run: jest --coverage=true --runInBand

  extra-node-version-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [21.x]
        os: [ubuntu-22.04]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4.0.1
        with:
          node-version: ${{ matrix.node-version }}


      - name: Install packages
        run: npm ci

      - name: Install Jest
        run: npm install --location=global jest

      - name: Calculate coverage
        run: jest --runInBand